### ISSUE TITLE
Fix entity pooling and recycling of "creeps"

### ISSUE THREAD

**Issue by sfoster** [sfoster/zed-gunner#1]
It looks like when those entities are returned from the pool, they are not properly reset. so they re-appear with data properties from their previous incarnation?

**Comment by grogbeard** [comment]
oooh classic technique. When they die, just have them slowly sink into the ground until they are low enough that they can't be seen and remove them. Oh you are talking about the redness! Yeah can verify, happens on my machine too.

**Comment by sfoster** [comment]
Got this fixed. The pool's request and restore methods just move the entities (elements) in and out of an array. So any cleanup and resetting of component state is up to the caller.
